version: '2'
services:  
  flask_base:
    build: ./flask_base
    restart: always
    command: uwsgi --processes=1 -M --gevent=100 --http-socket :80 -w devel:app
    ports:
      - 8081:80/tcp
    volumes:
      - '/var/log/flask_base:/var/log/flask_base/'
      - './share:/share'
    
