version: '2'
services:
  nginx:
    image: flask-base-nginx
    restart: always
    hostname: dev.kerrygao
    ports:
      - 80:80/tcp
    environment:
      - TZ=Asia/Shanghai
    mem_limit: 209715200
    links:
      - flask_base:service01 
  
  flask_base:
    image: 'flask_base'
    restart: always
    command: uwsgi --processes=1 -M --gevent=100 --http-socket :80 -w local:app
    volumes:
      - '/var/log/flask_base:/var/log/flask_base/'
      - './share:/share'
    mem_limit: 192m
    links:
      - mysql
    
  mysql:
    image: mysql:5.6
    container_name: flask_base_mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

     